INSERT INTO Item (id, title, itemType, description)
VALUES
    (1, 'Sword of Flames', 'WEAPON', 'A sword that engulfs its blade in flames, adding fire damage to attacks.'),
    (2, 'Healer''s Amulet', 'ACCESSORY', 'An amulet that boosts the wearer''s natural healing capabilities.'),
    (3, 'Boots of Swiftness', 'BOOTS', 'Magical boots that increase the wearer''s movement speed.'),
    (4, 'Cloak of Invisibility', 'MISC', 'A cloak that renders the wearer invisible when the hood is drawn over the head.'),
    (5, 'Ring of Strength', 'ACCESSORY', 'A ring that grants the wearer enhanced strength.'),
    (6, 'Robe of the Archmage', 'CHESTPLATE', 'A powerful robe that increases the wearer''s magical power.'),
    (7, 'Belt of Giant Strength', 'ACCESSORY', 'A belt that grants the wearer the strength of a giant.'),
    (8, 'Bow of Hunting', 'WEAPON', 'A bow that improves the wearer''s accuracy and damage on ranged attacks.'),
    (9, 'Staff of Healing', 'WEAPON', 'A staff that can be used to heal allies.'),
    (10, 'Vorpal Blade', 'WEAPON', 'A legendary sword with a chance to decapitate foes on a critical hit.'),
    (11, 'Gauntlets of Ogre Power', 'ACCESSORY', 'Gauntlets that increase the wearer''s physical power.'),
    (12, 'Helm of Telepathy', 'HELMET', 'A helm that allows the wearer to read thoughts.'),
    (13, 'Boots of Levitation', 'BOOTS', 'Boots that allow the wearer to levitate at will.'),
    (14, 'Mantle of Spell Resistance', 'CHESTPLATE', 'A mantle that grants resistance to magical spells.'),
    (15, 'Bracers of Archery', 'ACCESSORY', 'Bracers that improve the wearer''s archery skills.'),
    (16, 'Bag of Holding', 'MISC', 'A magical bag that can hold a vast number of items without increasing in weight.'),
    (17, 'Wand of Fireballs', 'WEAPON', 'A wand that can cast the fireball spell a certain number of times.'),
    (18, 'Necklace of Fireballs', 'ACCESSORY', 'A necklace with beads that can each be used to cast a fireball spell.'),
    (19, 'Elixir of Health', 'POTION', 'A potion that fully restores the drinker''s health.'),
    (20, 'Dagger of Venom', 'WEAPON', 'A dagger that poisons those it cuts.'),
    (21, 'Goggles of Night', 'ACCESSORY', 'Goggles that grant the wearer night vision.'),
    (22, 'Cape of the Mountebank', 'MISC', 'A cape that allows the wearer to teleport short distances.'),
    (23, 'Lyre of Building', 'MISC', 'A musical instrument that protects structures against decay.'),
    (24, 'Horn of Valhalla', 'MISC', 'A horn that summons spirit warriors when blown.'),
    (25, 'Decanter of Endless Water', 'MISC', 'A jug that produces an infinite amount of water.'),
    (26, 'Cube of Force', 'MISC', 'A cube that creates a barrier of force around the user.'),
    (27, 'Orb of Storms', 'MISC', 'An orb that can control local weather patterns.'),
    (28, 'Pearl of Power', 'ACCESSORY', 'A pearl that allows the user to recover expended spell slots.'),
    (29, 'Rod of Rulership', 'WEAPON', 'A rod that allows the user to charm others into following their commands.'),
    (30, 'Rope of Climbing', 'MISC', 'A rope that can be commanded to knot or unknot itself.'),
    (31, 'Slippers of Spider Climbing', 'BOOTS', 'Slippers that allow the wearer to climb walls and ceilings.'),
    (32, 'Stone of Good Luck', 'ACCESSORY', 'A stone that grants a bonus to all skill checks and saving throws.'),
    (33, 'Tome of Clear Thought', 'BOOK', 'A magical book that increases the reader''s Intelligence.'),
    (34, 'Wings of Flying', 'MISC', 'A pair of wings that grants the power of flight.'),
    (35, 'Lantern of Revealing', 'MISC', 'A lantern that illuminates invisible creatures and objects.'),
    (36, 'Mirror of Life Trapping', 'MISC', 'A mirror that can trap the souls of those who gaze into it.'),
    (37, 'Periapt of Wound Closure', 'ACCESSORY', 'A pendant that stabilizes the wearer when they are knocked unconscious.'),
    (38, 'Phylactery of Faithfulness', 'ACCESSORY', 'An item that alerts the wearer when they are about to make a moral misstep.'),
    (39, 'Pipes of Haunting', 'MISC', 'Musical pipes that can cause fear in those who hear them.'),
    (40, 'Quiver of Ehlonna', 'MISC', 'A magical quiver that can hold an enormous number of arrows.'),
    (41, 'Ring of Free Action', 'ACCESSORY', 'A ring that prevents magic from restricting the wearer''s movement.'),
    (42, 'Robe of Stars', 'CHESTPLATE', 'A robe that allows the wearer to travel to other planes of existence.'),
    (43, 'Scarab of Protection', 'ACCESSORY', 'A scarab that absorbs and nullifies curse, hex, or necrotic damage.'),
    (44, 'Sphere of Annihilation', 'MISC', 'A dangerous artifact that disintegrates anything it touches.'),
    (45, 'Figurine of Wondrous Power', 'MISC', 'A small statuette that can become a living creature for a short period.'),
    (46, 'Cloak of the Bat', 'MISC', 'A cloak that grants the wearer the ability to fly in low-light conditions.'),
    (47, 'Iron Flask', 'MISC', 'A flask capable of trapping extra-planar creatures.'),
    (48, 'Manual of Bodily Health', 'BOOK', 'A book that increases the reader''s Constitution.'),
    (49, 'Oathbow', 'WEAPON', 'An elven bow that swears vengeance on a declared enemy, granting bonus damage against the target.'),
    (50, 'Portable Hole', 'MISC', 'A circular piece of cloth that creates an extradimensional hole when spread out.');
