INSERT INTO Effect (id, type, duration, `range`, strength)
VALUES
    (1, 'PUSH', 1, 'ONE', 10),
    (2, 'PULL', 1, 'ONE', 10),
    (3, 'FORCED_MOVEMENT_IMMUNITY', 5, 'SELF', NULL),
    (4, 'POISON', 3, 'ONE', 5),
    (5, 'POISON_IMMUNITY', 10, 'SELF', NULL),
    (6, 'FIRE', 2, 'ONE', 15),
    (7, 'FIRE_IMMUNITY', 10, 'SELF', NULL),
    (8, 'BLEED', 4, 'ONE', 3),
    (9, 'BLEED_IMMUNITY', 10, 'SELF', NULL),
    (10, 'DISARM', 1, 'ONE', NULL),
    (11, 'DISARM_IMMUNITY', 10, 'SELF', NULL),
    (12, 'STUN', 1, 'ONE', NULL),
    (13, 'STUN_IMMUNITY', 5, 'SELF', NULL),
    (14, 'CONFUSION', 2, 'ONE', NULL),
    (15, 'CONFUSION_IMMUNITY', 10, 'SELF', NULL),
    (16, 'CHARM', 3, 'ONE', NULL),
    (17, 'CHARM_IMMUNITY', 10, 'SELF', NULL),
    (18, 'INVISIBILITY', 5, 'SELF', NULL),
    (19, 'SHIELD', 2, 'SELF', 10),
    (20, 'BONUS_HEALTH', 10, 'SELF', 20),
    (21, 'BONUS_DAMAGE', 5, 'SELF', 5),
    (22, 'BONUS_MOVEMENT', 5, 'SELF', 10);